FROM ubuntu:20.04
RUN apt update
RUN apt install sudo -y
RUN sudo apt update
RUN sudo apt-get update
RUN sudo apt install python3 python3-pip -y
RUN sudo apt-get -y install wget curl nano
RUN sudo apt-get -y install redis postgresql-12 
RUN pip install "apache-airflow[celery]==2.3.3" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.3.3/constraints-3.7.txt"

ENV AIRFLOW__CORE__EXECUTOR=CeleryExecutor
ENV AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
ENV AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
ENV AIRFLOW__CELERY__BROKER_URL=redis://:@redis:6379/0
ENV AIRFLOW__CORE__FERNET_KEY=""
ENV AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION="true"
ENV AIRFLOW__CORE__LOAD_EXAMPLES="fasle"
RUN sudo echo "0.0.0.0:5432	postgres" >> /etc/hosts
RUN sudo echo "0.0.0.0	redis" >> /etc/hosts
